# Beginning Steps

## Importing Original csv File

In [1]:
from pandas import read_csv
import pandas as pd

# Specify the encoding as 'latin-1' to handle the special characters
data = pd.read_csv('/content/retail_data.csv', encoding='latin-1') # Added encoding='latin-1'

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 78 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   customer_id                1000000 non-null  int64
 1   age                        1000000 non-null  int64
 2   gender                     1000000 non-null  object
 3   income_bracket             1000000 non-null  object
 4   loyalty_program            1000000 non-null  object
 5   membership_years           1000000 non-null  int64
 6   churned                    1000000 non-null  object
 7   marital_status             1000000 non-null  object
 8   number_of_children         1000000 non-null  int64
 9   education_level            1000000 non-null  object
 10  occupation                 1000000 non-null  object
 11  transaction_id             1000000 non-null  int64
 12  transaction_date           1000000 non-null  object
 13  product_id                 1000000 non-null  int64
 14  product_category           1000000 non-null  object
 15  quantity                   1000000 non-null  int64
 16  unit_price                 1000000 non-null  float64
 17  discount_applied           1000000 non-null  float64
 18  payment_method             1000000 non-null  object
 19  store_location             1000000 non-null  object
 20  transaction_hour           1000000 non-null  int64
 21  day_of_week                1000000 non-null  object
 22  week_of_year               1000000 non-null  int64
 23  month_of_year              1000000 non-null  int64
 24  avg_purchase_value         1000000 non-null  float64
 25  purchase_frequency         1000000 non-null  object
 26  last_purchase_date         1000000 non-null  object
 27  avg_discount_used          1000000 non-null  float64
 28  preferred_store            1000000 non-null  object
 29  online_purchases           1000000 non-null  int64
 30  in_store_purchases         1000000 non-null  int64
 31  avg_items_per_transaction  1000000 non-null  float64
 32  avg_transaction_value      1000000 non-null  float64
 33  total_returned_items       1000000 non-null  int64
 34  total_returned_value       1000000 non-null  float64
 35  total_sales                1000000 non-null  float64
 36  total_transactions         1000000 non-null  int64
 37  total_items_purchased      1000000 non-null  int64
 38  total_discounts_received   1000000 non-null  float64
 39  avg_spent_per_category     1000000 non-null  float64
 40  max_single_purchase_value  1000000 non-null  float64
 41  min_single_purchase_value  1000000 non-null  float64
 42  product_name               1000000 non-null  object
 43  product_brand              1000000 non-null  object
 44  product_rating             1000000 non-null  float64
 45  product_review_count       1000000 non-null  int64
 46  product_stock              1000000 non-null  int64
 47  product_return_rate        1000000 non-null  float64
 48  product_size               1000000 non-null  object
 49  product_weight             1000000 non-null  float64
 50  product_color              1000000 non-null  object
 51  product_material           1000000 non-null  object
 52  product_manufacture_date   1000000 non-null  object
 53  product_expiry_date        1000000 non-null  object
 54  product_shelf_life         1000000 non-null  int64
 55  promotion_id               1000000 non-null  int64
 56  promotion_type             1000000 non-null  object
 57  promotion_start_date       1000000 non-null  object
 58  promotion_end_date         1000000 non-null  object
 59  promotion_effectiveness    1000000 non-null  object
 60  promotion_channel          1000000 non-null  object
 61  promotion_target_audience  1000000 non-null  object
 62  customer_zip_code          1000000 non-null  int64
 63  customer_city              1000000 non-null  object
 64  customer_state             1000000 non-null  object
 65  store_zip_code             1000000 non-null  int64
 66  store_city                 1000000 non-null  object
 67  store_state                1000000 non-null  object
 68  distance_to_store          1000000 non-null  float64
 69  holiday_season             1000000 non-null  object
 70  season                     1000000 non-null  object
 71  weekend                    1000000 non-null  object
 72  customer_support_calls     1000000 non-null  int64
 73  email_subscriptions        1000000 non-null  object
 74  app_usage                  1000000 non-null  object
 75  website_visits             1000000 non-null  int64
 76  social_media_engagement    1000000 non-null  object
 77  days_since_last_purchase   1000000 non-null  int64
dtypes: float64(16), int64(24), object(38)
memory usage: 595.1+ MB

### Temporal Columns - Removal

In [3]:
temporal_columns = [
    'transaction_date',
    'last_purchase_date',
    'product_expiry_date',
    'product_manufacture_date',
    'promotion_start_date',
    'promotion_end_date'
]

print(data[temporal_columns].head(30))

       transaction_date   last_purchase_date  product_expiry_date  \
0   2020-10-11 10:08:52  2021-09-11 04:22:38  2022-05-28 14:54:02
1   2021-12-08 01:07:40  2021-05-16 12:01:16  2022-12-19 08:04:41
2   2020-02-17 09:40:48  2021-02-07 16:47:48  2023-02-01 12:15:07
3   2020-08-13 00:43:14  2021-12-30 23:48:26  2023-02-05 11:46:57
4   2021-07-02 11:59:03  2021-11-02 11:48:25  2023-10-05 08:13:07
5   2020-12-01 16:31:54  2021-09-22 18:23:28  2022-10-31 01:48:25
6   2020-03-14 22:58:48  2021-08-08 21:30:47  2023-11-04 17:03:25
7   2021-11-17 15:56:04  2021-12-31 23:40:55  2022-01-24 05:50:56
8   2020-05-18 08:48:18  2021-04-16 23:26:21  2022-10-04 03:00:26
9   2020-03-10 18:03:08  2021-08-17 06:19:23  2022-02-20 12:19:26
10  2021-10-13 08:07:17  2021-11-13 12:11:26  2022-03-12 11:30:26
11  2021-01-26 14:31:38  2021-09-11 12:30:17  2022-12-11 20:03:58
12  2021-04-01 14:27:15  2021-05-03 01:51:33  2023-10-31 08:14:56
13  2020-12-08 12:50:49  2021-01-04 14:49:44  2022-10-24 23:49:44
14  2021-06-17 09:35:20  2021-01-11 23:09:33  2022-05-10 12:47:26
15  2021-06-08 17:28:08  2021-03-15 22:02:13  2022-02-12 12:43:22
16  2021-06-11 03:32:41  2021-11-09 03:08:19  2023-03-19 12:07:32
17  2020-05-28 00:36:24  2021-06-16 18:54:43  2023-12-08 00:14:04
18  2021-09-05 05:21:54  2021-12-05 12:42:18  2023-10-31 23:17:59
19  2021-08-11 22:50:13  2021-07-29 15:58:29  2023-07-07 02:17:40
20  2020-07-04 12:42:16  2021-12-05 04:22:35  2022-10-20 15:44:46
21  2020-02-28 12:33:05  2021-05-02 04:02:48  2022-07-15 00:30:04
22  2021-11-08 21:20:37  2021-12-08 12:06:34  2023-07-14 05:35:27
23  2020-06-14 04:24:04  2021-08-25 11:39:25  2022-07-26 17:22:44
24  2020-05-25 16:21:01  2021-12-14 07:01:56  2022-07-30 21:11:18
25  2020-02-08 02:45:45  2021-05-19 01:31:16  2022-06-09 13:43:36
26  2020-08-06 16:52:36  2021-04-24 14:21:34  2023-03-01 18:35:45
27  2021-03-06 22:31:28  2021-06-26 04:42:46  2022-04-09 02:59:43
28  2021-03-27 13:44:19  2021-03-10 18:14:41  2023-05-16 01:43:05
29  2021-08-24 16:23:51  2021-11-04 23:39:10  2023-01-22 09:39:31

   product_manufacture_date promotion_start_date   promotion_end_date
0       2019-08-04 01:47:01  2021-07-14 14:28:42  2022-12-30 13:04:13
1       2019-10-23 19:59:17  2021-09-23 04:26:09  2022-09-13 03:16:26
2       2018-05-12 08:00:29  2021-06-13 12:31:15  2022-03-13 00:53:35
3       2019-11-15 16:17:29  2021-05-23 05:42:48  2022-02-06 00:42:30
4       2019-08-27 02:58:19  2021-04-19 04:55:32  2022-12-04 13:07:09
5       2019-02-09 22:23:36  2021-06-22 22:55:54  2022-05-11 04:36:17
6       2018-12-14 12:35:24  2021-06-07 16:39:20  2022-11-04 11:10:31
7       2018-01-06 22:13:14  2021-01-22 12:56:56  2022-03-02 03:29:31
8       2018-12-25 09:49:50  2021-05-30 14:38:58  2022-07-12 07:53:21
9       2018-02-27 19:00:28  2021-03-29 15:56:01  2022-12-31 14:47:35
10      2018-08-09 08:43:14  2021-06-09 08:29:58  2022-12-23 10:22:14
11      2019-12-02 11:35:43  2021-07-10 06:45:07  2022-12-02 08:27:29
12      2019-07-24 18:30:24  2021-11-11 02:23:25  2022-08-27 09:11:03
13      2018-06-02 00:12:15  2021-06-07 07:51:49  2022-12-15 22:22:09
14      2018-03-31 01:41:59  2021-07-16 13:25:38  2022-04-10 15:28:39
15      2018-06-19 14:24:53  2021-07-23 04:19:26  2022-07-22 14:47:39
16      2019-12-20 23:34:21  2021-05-15 12:02:53  2022-07-17 00:27:04
17      2019-09-07 19:12:06  2021-07-03 12:24:41  2022-08-15 19:11:12
18      2018-08-12 00:04:32  2021-11-19 05:11:51  2022-11-11 20:29:47
19      2019-05-06 15:48:59  2021-06-15 17:39:46  2022-08-08 14:11:21
20      2019-11-06 23:13:17  2021-04-10 14:49:38  2022-08-13 06:20:14
21      2018-02-26 11:46:49  2021-08-28 16:02:41  2022-07-26 07:52:49
22      2018-07-29 16:14:37  2021-07-15 18:15:39  2022-07-09 06:37:01
23      2018-08-05 17:57:25  2021-03-31 13:11:27  2022-08-21 12:02:19
24      2019-03-20 21:07:59  2021-04-19 15:22:21  2022-05-21 10:13:07
25      2018-10-03 19:03:23  2021-07-22 03:18:10  2022-05-10 19:11:29
26      2018-11-04 09:09:44  2021-08-08 08:33:03  2022-05-24 11:35:10
27      2019-06-30 04:56:40  2021-06-07 12:51:10  2022-09-07 15:28:25
28      2018-05-27 19:33:06  2021-07-30 18:47:36  2022-04-23 15:15:10
29      2018-05-24 10:35:11  2021-01-25 18:14:45  2022-03-01 21:07:49

In [4]:
#NOT chrological

In [5]:
import pandas as pd

temporal_columns = [
    'transaction_date',
    'last_purchase_date',
    'product_expiry_date',
    'product_manufacture_date',
    'promotion_start_date',
    'promotion_end_date'
]

# Ensure the temporal columns exist in the DataFrame before processing
existing_temporal_columns = [col for col in temporal_columns if col in data.columns]

# Convert temporal columns to datetime objects
# Use errors='coerce' to turn any unparseable dates into NaT (Not a Time)
for col in existing_temporal_columns:
    data[col] = pd.to_datetime(data[col], errors='coerce')

print("Minimum and Maximum Dates for Temporal Columns:")
for col in existing_temporal_columns:
    min_date = data[col].min()
    max_date = data[col].max()
    print(f"\n--- {col} ---")
    print(f"Min Date: {min_date}")
    print(f"Max Date: {max_date}")

Minimum and Maximum Dates for Temporal Columns:

--- transaction_date ---
Min Date: 2020-01-01 00:00:21
Max Date: 2021-12-31 23:58:32

--- last_purchase_date ---
Min Date: 2021-01-01 00:00:17
Max Date: 2021-12-31 23:59:25

--- product_expiry_date ---
Min Date: 2022-01-01 00:00:14
Max Date: 2023-12-31 23:59:36

--- product_manufacture_date ---
Min Date: 2018-01-01 00:00:10
Max Date: 2019-12-31 23:59:14

--- promotion_start_date ---
Min Date: 2021-01-01 00:01:36
Max Date: 2021-12-31 23:59:18

--- promotion_end_date ---
Min Date: 2022-01-01 00:00:02
Max Date: 2022-12-31 23:59:26

In [6]:
# Define temporal attributes to remove
temporal_columns = [
    'transaction_date',
    'last_purchase_date',
    'product_expiry_date',
    'product_manufacture_date',
    'promotion_start_date',
    'promotion_end_date'
]

# Remove temporal attributes
data = data.drop(columns=[col for col in temporal_columns if col in data.columns])

# Verify columns after removal
print("Columns after removing temporal attributes:", data.columns.tolist())

Columns after removing temporal attributes: ['customer_id', 'age', 'gender', 'income_bracket', 'loyalty_program', 'membership_years', 'churned', 'marital_status', 'number_of_children', 'education_level', 'occupation', 'transaction_id', 'product_id', 'product_category', 'quantity', 'unit_price', 'discount_applied', 'payment_method', 'store_location', 'transaction_hour', 'day_of_week', 'week_of_year', 'month_of_year', 'avg_purchase_value', 'purchase_frequency', 'avg_discount_used', 'preferred_store', 'online_purchases', 'in_store_purchases', 'avg_items_per_transaction', 'avg_transaction_value', 'total_returned_items', 'total_returned_value', 'total_sales', 'total_transactions', 'total_items_purchased', 'total_discounts_received', 'avg_spent_per_category', 'max_single_purchase_value', 'min_single_purchase_value', 'product_name', 'product_brand', 'product_rating', 'product_review_count', 'product_stock', 'product_return_rate', 'product_size', 'product_weight', 'product_color', 'product_material', 'product_shelf_life', 'promotion_id', 'promotion_type', 'promotion_effectiveness', 'promotion_channel', 'promotion_target_audience', 'customer_zip_code', 'customer_city', 'customer_state', 'store_zip_code', 'store_city', 'store_state', 'distance_to_store', 'holiday_season', 'season', 'weekend', 'customer_support_calls', 'email_subscriptions', 'app_usage', 'website_visits', 'social_media_engagement', 'days_since_last_purchase']

## Descriptive Statistics on all attributes

In [7]:
# Display all columns when printing DataFrame
pd.set_option('display.max_columns', None)


import pandas as pd

# Assuming your DataFrame is named 'data'
# Get all columns from the DataFrame
all_columns = data.columns.tolist()

# Verify the number of columns
print(f"Total columns in DataFrame: {len(all_columns)}")
print("Columns:", all_columns)

from sklearn.model_selection import train_test_split
X_train, X_test, _, _ = train_test_split(data, data.index, test_size=0.3, random_state=42)

# Generate descriptive statistics for numerical columns (int64, float64)
numerical_columns = data.select_dtypes(include=['int64', 'float64']).columns
numerical_stats = data[numerical_columns].describe()

# Generate descriptive statistics for categorical columns (object)
categorical_columns = data.select_dtypes(include=['object']).columns
categorical_stats = data[categorical_columns].describe()

# Print the statistics
print("\nNumerical Columns Statistics:")
print(numerical_stats)
print("\nCategorical Columns Statistics:")
print(categorical_stats)

Total columns in DataFrame: 72
Columns: ['customer_id', 'age', 'gender', 'income_bracket', 'loyalty_program', 'membership_years', 'churned', 'marital_status', 'number_of_children', 'education_level', 'occupation', 'transaction_id', 'product_id', 'product_category', 'quantity', 'unit_price', 'discount_applied', 'payment_method', 'store_location', 'transaction_hour', 'day_of_week', 'week_of_year', 'month_of_year', 'avg_purchase_value', 'purchase_frequency', 'avg_discount_used', 'preferred_store', 'online_purchases', 'in_store_purchases', 'avg_items_per_transaction', 'avg_transaction_value', 'total_returned_items', 'total_returned_value', 'total_sales', 'total_transactions', 'total_items_purchased', 'total_discounts_received', 'avg_spent_per_category', 'max_single_purchase_value', 'min_single_purchase_value', 'product_name', 'product_brand', 'product_rating', 'product_review_count', 'product_stock', 'product_return_rate', 'product_size', 'product_weight', 'product_color', 'product_material', 'product_shelf_life', 'promotion_id', 'promotion_type', 'promotion_effectiveness', 'promotion_channel', 'promotion_target_audience', 'customer_zip_code', 'customer_city', 'customer_state', 'store_zip_code', 'store_city', 'store_state', 'distance_to_store', 'holiday_season', 'season', 'weekend', 'customer_support_calls', 'email_subscriptions', 'app_usage', 'website_visits', 'social_media_engagement', 'days_since_last_purchase']

Numerical Columns Statistics:
          customer_id             age  membership_years  number_of_children  \
count  1000000.000000  1000000.000000    1000000.000000      1000000.000000
mean    500000.500000       48.496605          4.497453            2.000554
std     288675.278933       17.874381          2.872406            1.414214
min          1.000000       18.000000          0.000000            0.000000
25%     250000.750000       33.000000          2.000000            1.000000
50%     500000.500000       49.000000          4.000000            2.000000
75%     750000.250000       64.000000          7.000000            3.000000
max    1000000.000000       79.000000          9.000000            4.000000

       transaction_id      product_id        quantity      unit_price  \
count  1000000.000000  1000000.000000  1000000.000000  1000000.000000
mean    499891.731447     4999.564515        5.002649      500.261317
std     288706.057652     2886.798391        2.583751      288.462860
min          2.000000        1.000000        1.000000        1.000000
25%     249878.750000     2498.000000        3.000000      250.310000
50%     499559.500000     4999.000000        5.000000      500.410000
75%     750071.250000     7498.000000        7.000000      750.160000
max     999999.000000     9999.000000        9.000000     1000.000000

       discount_applied  transaction_hour    week_of_year   month_of_year  \
count    1000000.000000    1000000.000000  1000000.000000  1000000.000000
mean           0.249910         11.505193       26.503691        6.497467
std            0.144328          6.924460       15.005165        3.455212
min            0.000000          0.000000        1.000000        1.000000
25%            0.130000          5.000000       14.000000        3.000000
50%            0.250000         12.000000       27.000000        7.000000
75%            0.370000         18.000000       39.000000       10.000000
max            0.500000         23.000000       52.000000       12.000000

       avg_purchase_value  avg_discount_used  online_purchases  \
count      1000000.000000     1000000.000000    1000000.000000
mean           254.886444           0.250010         49.446018
std            141.494923           0.144383         28.861439
min             10.000000           0.000000          0.000000
25%            132.220000           0.130000         24.000000
50%            254.930000           0.250000         49.000000
75%            377.350000           0.380000         74.000000
max            500.000000           0.500000         99.000000

       in_store_purchases  avg_items_per_transaction  avg_transaction_value  \
count      1000000.000000             1000000.000000         1000000.000000
mean            49.484486                   5.503122             255.115768
std             28.882712                   2.597661             141.430014
min              0.000000                   1.000000              10.000000
25%             24.000000                   3.260000             132.510000
50%             49.000000                   5.500000             255.230000
75%             75.000000                   7.750000             377.670000
max             99.000000                  10.000000             500.000000

       total_returned_items  total_returned_value     total_sales  \
count        1000000.000000        1000000.000000  1000000.000000
mean               4.498142            500.387837     5056.059765
std                2.872805            288.717476     2859.100058
min                0.000000              0.000000      100.010000
25%                2.000000            250.630000     2577.867500
50%                4.000000            500.400000     5059.695000
75%                7.000000            750.390000     7534.802500
max                9.000000           1000.000000     9999.980000

       total_transactions  total_items_purchased  total_discounts_received  \
count      1000000.000000         1000000.000000            1000000.000000
mean            49.987386             250.042763                499.674388
std             28.571689             143.984546                288.579102
min              1.000000               1.000000                  0.000000
25%             25.000000             125.000000                249.760000
50%             50.000000             250.000000                499.510000
75%             75.000000             375.000000                749.540000
max             99.000000             499.000000               1000.000000

       avg_spent_per_category  max_single_purchase_value  \
count          1000000.000000             1000000.000000
mean               505.175478                 505.001404
std                286.059178                 286.073324
min                 10.000000                  10.000000
25%                257.240000                 256.840000
50%                505.140000                 505.220000
75%                753.060000                 753.210000
max               1000.000000                1000.000000

       min_single_purchase_value  product_rating  product_review_count  \
count             1000000.000000  1000000.000000        1000000.000000
mean                    5.043849        2.999010            499.235198
std                     2.855905        1.154801            288.446150
min                     0.100000        1.000000              0.000000
25%                     2.570000        2.000000            250.000000
50%                     5.040000        3.000000            499.000000
75%                     7.510000        4.000000            749.000000
max                    10.000000        5.000000            999.000000

        product_stock  product_return_rate  product_weight  \
count  1000000.000000       1000000.000000  1000000.000000
mean        49.515129             0.250137        5.054372
std         28.876645             0.144408        2.857848
min          0.000000             0.000000        0.100000
25%         25.000000             0.130000        2.580000
50%         49.000000             0.250000        5.060000
75%         75.000000             0.380000        7.530000
max         99.000000             0.500000       10.000000

       product_shelf_life    promotion_id  customer_zip_code  store_zip_code  \
count      1000000.000000  1000000.000000     1000000.000000  1000000.000000
mean           181.876207      499.920037       54993.644773    54972.766714
std            105.228855      288.453056       25975.807799    25981.483139
min              0.000000        1.000000       10000.000000    10000.000000
25%             91.000000      250.000000       32477.750000    32473.000000
50%            182.000000      500.000000       54966.000000    54961.000000
75%            273.000000      750.000000       77493.000000    77451.000000
max            364.000000      999.000000       99998.000000    99998.000000

       distance_to_store  customer_support_calls  website_visits  \
count     1000000.000000          1000000.000000  1000000.000000
mean           49.979109                9.496269       49.512951
std            28.860989                5.761233       28.869777
min             0.000000                0.000000        0.000000
25%            24.970000                4.000000       25.000000
50%            49.960000                9.000000       50.000000
75%            74.950000               14.000000       75.000000
max           100.000000               19.000000       99.000000

       days_since_last_purchase
count            1000000.000000
mean                 182.027559
std                  105.364598
min                    0.000000
25%                   91.000000
50%                  182.000000
75%                  273.000000
max                  364.000000

Categorical Columns Statistics:
         gender income_bracket loyalty_program  churned marital_status  \
count   1000000        1000000         1000000  1000000        1000000
unique        3              3               2        2              3
top       Other           High              No       No       Divorced
freq     333734         333612          500288   500271         333816

       education_level occupation product_category payment_method  \
count          1000000    1000000          1000000        1000000
unique               4          4                5              4
top         Bachelor's   Employed             Toys    Credit Card
freq            250360     250857           200669         250435

       store_location day_of_week purchase_frequency preferred_store  \
count         1000000     1000000            1000000         1000000
unique              4           7                  4               4
top        Location C     Tuesday             Yearly      Location B
freq           250336      143452             250767          250262

       product_name product_brand product_size product_color product_material  \
count       1000000       1000000      1000000       1000000          1000000
unique            4             3            3             5                4
top       Product B       Brand Y        Large          Blue          Plastic
freq         250375        333775       333964        200671           250483

       promotion_type promotion_effectiveness promotion_channel  \
count         1000000                 1000000           1000000
unique              3                       3                 3
top           20% Off                    High            Online
freq           333712                  333660            333694

       promotion_target_audience customer_city customer_state store_city  \
count                    1000000       1000000        1000000    1000000
unique                         2             4              3          4
top                New Customers        City B        State Z     City D
freq                      500118        250788         333674     250315

       store_state holiday_season   season  weekend email_subscriptions  \
count      1000000        1000000  1000000  1000000             1000000
unique           3              2        4        2                   2
top        State X            Yes   Winter       No                  No
freq        333702         500214   250307   500667              500062

       app_usage social_media_engagement
count    1000000                 1000000
unique         3                       3
top       Medium                     Low
freq      333822                  334073

# Data Preprocessing

## Sampling to 20,000 Records - Simple Random Sampling

In [8]:
import pandas as pd

# Check if data has more than or equal to 20000 rows
sample_size = min(20000, len(data))  # Sample 20,000 rows

# Sample the data
sampled_data = data.sample(n=sample_size, random_state=42)

# Display the sampled data
print(sampled_data)

        customer_id  age  gender income_bracket loyalty_program  \
987231       987232   60  Female         Medium             Yes
79954         79955   63   Other            Low              No
567130       567131   72   Other         Medium             Yes
500891       500892   34   Other           High             Yes
55399         55400   77   Other         Medium              No
...             ...  ...     ...            ...             ...
915278       915279   19    Male            Low              No
30783         30784   34   Other            Low             Yes
239876       239877   77    Male           High              No
160215       160216   27  Female            Low              No
809896       809897   39    Male         Medium              No

        membership_years churned marital_status  number_of_children  \
987231                 8     Yes       Divorced                   3
79954                  1     Yes         Single                   0
567130                 0      No         Single                   4
500891                 3      No       Divorced                   3
55399                  3      No         Single                   4
...                  ...     ...            ...                 ...
915278                 0     Yes         Single                   2
30783                  4      No        Married                   4
239876                 5     Yes         Single                   2
160215                 5     Yes         Single                   0
809896                 6     Yes         Single                   4

       education_level     occupation  transaction_id  product_id  \
987231        Master's     Unemployed          877066        6421
79954      High School       Employed          689209        6876
567130     High School     Unemployed          956501        2402
500891        Master's       Employed          374436        8353
55399         Master's        Retired          311416        8019
...                ...            ...             ...         ...
915278        Master's       Employed           42297        2162
30783      High School  Self-Employed          444507        7501
239876      Bachelor's     Unemployed          910196        9547
160215             PhD       Employed          826777        4355
809896        Master's     Unemployed          457404        9583

       product_category  quantity  unit_price  discount_applied  \
987231        Groceries         4      171.92              0.10
79954              Toys         7      453.50              0.01
567130             Toys         4      820.36              0.03
500891         Clothing         5       39.93              0.45
55399         Groceries         1       90.38              0.15
...                 ...       ...         ...               ...
915278        Furniture         8       28.26              0.41
30783              Toys         2      337.20              0.49
239876        Groceries         4      355.57              0.41
160215        Furniture         1      406.83              0.03
809896        Furniture         3      653.51              0.38

        payment_method store_location  transaction_hour day_of_week  \
987231            Cash     Location D                14    Saturday
79954             Cash     Location D                 0    Saturday
567130  Mobile Payment     Location A                16    Saturday
500891      Debit Card     Location A                20     Tuesday
55399             Cash     Location A                 9     Tuesday
...                ...            ...               ...         ...
915278      Debit Card     Location A                22   Wednesday
30783   Mobile Payment     Location C                14    Saturday
239876      Debit Card     Location D                 4     Tuesday
160215  Mobile Payment     Location C                16    Thursday
809896      Debit Card     Location A                11    Thursday

        week_of_year  month_of_year  avg_purchase_value purchase_frequency  \
987231            47              7              460.29             Weekly
79954              8             10              471.25            Monthly
567130            27              8              200.59             Weekly
500891            18              6              416.72             Weekly
55399             27             10              180.79              Daily
...              ...            ...                 ...                ...
915278            14             12              229.11              Daily
30783             41              7               97.49             Yearly
239876            20              1              235.95             Yearly
160215             7              6              478.83             Weekly
809896            41              3              237.42              Daily

        avg_discount_used preferred_store  online_purchases  \
987231               0.49      Location D                96
79954                0.36      Location B                38
567130               0.24      Location C                65
500891               0.43      Location A                54
55399                0.48      Location C                79
...                   ...             ...               ...
915278               0.17      Location B                24
30783                0.23      Location B                57
239876               0.33      Location B                24
160215               0.48      Location C                94
809896               0.50      Location D                48

        in_store_purchases  avg_items_per_transaction  avg_transaction_value  \
987231                  78                       1.70                 374.84
79954                   19                       5.96                 127.35
567130                  37                       3.22                 190.46
500891                  29                       3.24                 304.81
55399                   27                       9.76                 136.49
...                    ...                        ...                    ...
915278                  60                       2.69                 370.10
30783                   35                       5.98                 106.34
239876                  78                       3.31                 300.36
160215                  15                       1.50                 206.38
809896                  20                       5.84                 112.33

        total_returned_items  total_returned_value  total_sales  \
987231                     5                170.41      4417.26
79954                      0                970.63      3469.66
567130                     8                219.24      6771.43
500891                     5                723.65      9397.70
55399                      6                 32.39      5740.08
...                      ...                   ...          ...
915278                     7                139.88      9035.06
30783                      1                150.86      7698.72
239876                     7                180.03      5942.93
160215                     3                650.46      2860.19
809896                     4                768.97      7676.50

        total_transactions  total_items_purchased  total_discounts_received  \
987231                   9                    454                    263.01
79954                   40                    455                    104.15
567130                  60                    493                    428.12
500891                  11                    196                    245.91
55399                   17                     35                    464.84
...                    ...                    ...                       ...
915278                  95                    300                    972.86
30783                   66                    464                    538.84
239876                  92                    311                    176.47
160215                  24                     18                    696.63
809896                  11                    464                    476.10

        avg_spent_per_category  max_single_purchase_value  \
987231                   99.19                     708.86
79954                   141.69                     437.76
567130                  162.92                     925.22
500891                  241.16                     373.23
55399                   165.24                     189.51
...                        ...                        ...
915278                  811.90                     722.51
30783                   896.93                     720.54
239876                  163.78                     665.68
160215                  709.73                     374.57
809896                  157.57                     118.72

        min_single_purchase_value product_name product_brand  product_rating  \
987231                       6.35    Product C       Brand Y             2.0
79954                        0.99    Product A       Brand Y             4.3
567130                       2.77    Product C       Brand Z             1.6
500891                       6.03    Product C       Brand Y             1.8
55399                        8.59    Product B       Brand X             2.0
...                           ...          ...           ...             ...
915278                       2.83    Product A       Brand X             1.5
30783                        4.81    Product B       Brand Z             3.9
239876                       1.43    Product B       Brand Z             2.7
160215                       8.45    Product C       Brand X             1.4
809896                       7.58    Product A       Brand Z             1.8

        product_review_count  product_stock  product_return_rate product_size  \
987231                   122             97                 0.41        Small
79954                    547             98                 0.10       Medium
567130                   191             80                 0.34        Large
500891                    44             76                 0.41        Small
55399                    140             40                 0.07        Large
...                      ...            ...                  ...          ...
915278                   939             74                 0.42       Medium
30783                    263             88                 0.34        Large
239876                    72             10                 0.10       Medium
160215                   937             47                 0.21        Large
809896                   575             86                 0.36        Small

        product_weight product_color product_material  product_shelf_life  \
987231            8.17         Green            Metal                  45
79954             6.41           Red            Metal                  95
567130            0.23         Green             Wood                 127
500891            6.05         Black             Wood                 295
55399             4.70           Red             Wood                 136
...                ...           ...              ...                 ...
915278            1.45         Black            Metal                 174
30783             1.53           Red            Glass                 130
239876            2.90         White            Metal                  52
160215            7.38         White            Glass                  83
809896            1.22         Green            Glass                 130

        promotion_id        promotion_type promotion_effectiveness  \
987231           224               20% Off                  Medium
79954             55               20% Off                    High
567130           927  Buy One Get One Free                     Low
500891           960            Flash Sale                    High
55399            703               20% Off                    High
...              ...                   ...                     ...
915278           182            Flash Sale                  Medium
30783            163               20% Off                    High
239876           953            Flash Sale                  Medium
160215           739               20% Off                     Low
809896           383               20% Off                    High

       promotion_channel promotion_target_audience  customer_zip_code  \
987231          In-store             New Customers              80058
79954             Online       Returning Customers              44615
567130      Social Media             New Customers              88364
500891          In-store       Returning Customers              99239
55399             Online             New Customers              81746
...                  ...                       ...                ...
915278          In-store       Returning Customers              77861
30783             Online             New Customers              60251
239876      Social Media             New Customers              80831
160215          In-store             New Customers              10309
809896          In-store       Returning Customers              53235

       customer_city customer_state  store_zip_code store_city store_state  \
987231        City B        State X           56951     City C     State Z
79954         City A        State Y           67849     City A     State Y
567130        City D        State Y           19181     City A     State X
500891        City D        State Y           98115     City C     State Y
55399         City C        State Z           59365     City A     State Z
...              ...            ...             ...        ...         ...
915278        City C        State Y           14546     City B     State Y
30783         City B        State X           34618     City D     State X
239876        City C        State Y           32122     City B     State X
160215        City C        State Z           36459     City C     State X
809896        City C        State X           76828     City C     State Y

        distance_to_store holiday_season  season weekend  \
987231              76.72            Yes  Summer     Yes
79954               46.77             No  Winter     Yes
567130              31.77            Yes  Spring     Yes
500891              94.25             No  Summer     Yes
55399               52.19            Yes  Spring      No
...                   ...            ...     ...     ...
915278              21.85             No  Summer      No
30783               67.89             No  Winter     Yes
239876              73.55             No  Spring      No
160215              59.80            Yes    Fall      No
809896              55.76            Yes  Summer      No

        customer_support_calls email_subscriptions app_usage  website_visits  \
987231                       1                 Yes       Low              75
79954                        3                 Yes    Medium              77
567130                      14                 Yes    Medium              52
500891                       7                 Yes       Low              21
55399                       17                  No       Low              69
...                        ...                 ...       ...             ...
915278                       5                 Yes      High              40
30783                        5                 Yes    Medium              38
239876                       6                 Yes      High              89
160215                      18                  No       Low              46
809896                       8                  No    Medium               2

       social_media_engagement  days_since_last_purchase
987231                    High                       329
79954                     High                       145
567130                     Low                        95
500891                     Low                       124
55399                      Low                       240
...                        ...                       ...
915278                  Medium                       179
30783                     High                       158
239876                    High                       182
160215                    High                       218
809896                     Low                       301

[20000 rows x 72 columns]

## Statistical Verification to Confirm Representativeness for Comparing Full & Simple Random Sampling Datasets

In [9]:
# Display all columns when printing DataFrame
pd.set_option('display.max_columns', None)


import pandas as pd

# Assuming your DataFrame is named 'sampled_data'
# Get all columns from the DataFrame
all_columns = sampled_data.columns.tolist()

# Verify the number of columns
print(f"Total columns in DataFrame: {len(all_columns)}")
print("Columns:", all_columns)

# Generate descriptive statistics for numerical columns (int64, float64)
numerical_columns = sampled_data.select_dtypes(include=['int64', 'float64']).columns
numerical_stats = sampled_data[numerical_columns].describe()

# Generate descriptive statistics for categorical columns (object)
categorical_columns = sampled_data.select_dtypes(include=['object']).columns
categorical_stats = sampled_data[categorical_columns].describe()

# Print the statistics
print("\nNumerical Columns Statistics:")
print(numerical_stats)
print("\nCategorical Columns Statistics:")
print(categorical_stats)

Total columns in DataFrame: 72
Columns: ['customer_id', 'age', 'gender', 'income_bracket', 'loyalty_program', 'membership_years', 'churned', 'marital_status', 'number_of_children', 'education_level', 'occupation', 'transaction_id', 'product_id', 'product_category', 'quantity', 'unit_price', 'discount_applied', 'payment_method', 'store_location', 'transaction_hour', 'day_of_week', 'week_of_year', 'month_of_year', 'avg_purchase_value', 'purchase_frequency', 'avg_discount_used', 'preferred_store', 'online_purchases', 'in_store_purchases', 'avg_items_per_transaction', 'avg_transaction_value', 'total_returned_items', 'total_returned_value', 'total_sales', 'total_transactions', 'total_items_purchased', 'total_discounts_received', 'avg_spent_per_category', 'max_single_purchase_value', 'min_single_purchase_value', 'product_name', 'product_brand', 'product_rating', 'product_review_count', 'product_stock', 'product_return_rate', 'product_size', 'product_weight', 'product_color', 'product_material', 'product_shelf_life', 'promotion_id', 'promotion_type', 'promotion_effectiveness', 'promotion_channel', 'promotion_target_audience', 'customer_zip_code', 'customer_city', 'customer_state', 'store_zip_code', 'store_city', 'store_state', 'distance_to_store', 'holiday_season', 'season', 'weekend', 'customer_support_calls', 'email_subscriptions', 'app_usage', 'website_visits', 'social_media_engagement', 'days_since_last_purchase']

Numerical Columns Statistics:
         customer_id           age  membership_years  number_of_children  \
count   20000.000000  20000.000000      20000.000000        20000.000000
mean   499289.111500     48.632650          4.482650            1.986800
std    288930.140912     17.968802          2.863461            1.407986
min        32.000000     18.000000          0.000000            0.000000
25%    249060.250000     33.000000          2.000000            1.000000
50%    498793.500000     49.000000          5.000000            2.000000
75%    750988.000000     64.000000          7.000000            3.000000
max    999998.000000     79.000000          9.000000            4.000000

       transaction_id    product_id      quantity    unit_price  \
count    20000.000000  20000.000000  20000.000000  20000.000000
mean    500528.978950   4974.405650      5.004450    498.323781
std     288038.002979   2884.483246      2.588719    289.309285
min         11.000000      1.000000      1.000000      1.000000
25%     254204.000000   2486.750000      3.000000    245.227500
50%     500069.000000   4941.000000      5.000000    497.670000
75%     750157.750000   7466.000000      7.000000    751.532500
max     999898.000000   9999.000000      9.000000    999.990000

       discount_applied  transaction_hour  week_of_year  month_of_year  \
count      20000.000000      20000.000000  20000.000000   20000.000000
mean           0.248495         11.548050     26.278150       6.474400
std            0.144706          6.909622     15.040688       3.472715
min            0.000000          0.000000      1.000000       1.000000
25%            0.120000          6.000000     13.000000       3.000000
50%            0.250000         12.000000     26.000000       6.000000
75%            0.370000         18.000000     39.000000      10.000000
max            0.500000         23.000000     52.000000      12.000000

       avg_purchase_value  avg_discount_used  online_purchases  \
count        20000.000000       20000.000000      20000.000000
mean           254.924783           0.250688         49.538750
std            142.250643           0.144774         29.015001
min             10.030000           0.000000          0.000000
25%            131.627500           0.130000         24.000000
50%            255.105000           0.250000         50.000000
75%            379.347500           0.380000         75.000000
max            499.960000           0.500000         99.000000

       in_store_purchases  avg_items_per_transaction  avg_transaction_value  \
count        20000.000000               20000.000000           20000.000000
mean            49.390750                   5.498453             256.596209
std             28.857554                   2.594727             141.344702
min              0.000000                   1.000000              10.010000
25%             24.000000                   3.230000             133.837500
50%             49.000000                   5.510000             257.310000
75%             74.000000                   7.720000             378.855000
max             99.000000                  10.000000             499.980000

       total_returned_items  total_returned_value   total_sales  \
count          20000.000000          20000.000000  20000.000000
mean               4.441650            502.026042   5068.045273
std                2.877518            288.055798   2855.311437
min                0.000000              0.020000    100.280000
25%                2.000000            252.305000   2593.340000
50%                4.000000            501.020000   5082.490000
75%                7.000000            750.315000   7531.472500
max                9.000000            999.930000   9999.790000

       total_transactions  total_items_purchased  total_discounts_received  \
count        20000.000000           20000.000000              20000.000000
mean            49.866500             250.224400                498.824893
std             28.660632             144.026381                288.760143
min              1.000000               1.000000                  0.050000
25%             25.000000             127.000000                247.290000
50%             50.000000             250.000000                498.255000
75%             75.000000             374.000000                747.585000
max             99.000000             499.000000                999.980000

       avg_spent_per_category  max_single_purchase_value  \
count            20000.000000               20000.000000
mean               507.819163                 507.754567
std                287.274687                 284.801850
min                 10.060000                  10.020000
25%                260.192500                 261.147500
50%                508.840000                 511.435000
75%                757.515000                 754.492500
max               1000.000000                 999.990000

       min_single_purchase_value  product_rating  product_review_count  \
count               20000.000000    20000.000000           20000.00000
mean                    5.015788        3.000760             498.44190
std                     2.874322        1.153946             289.18613
min                     0.100000        1.000000               0.00000
25%                     2.500000        2.000000             248.00000
50%                     5.020000        3.000000             495.00000
75%                     7.490000        4.000000             751.00000
max                    10.000000        5.000000             999.00000

       product_stock  product_return_rate  product_weight  product_shelf_life  \
count   20000.000000         20000.000000    20000.000000        20000.000000
mean       49.477800             0.250242        5.032161          182.212500
std        29.000282             0.145123        2.853909          105.200252
min         0.000000             0.000000        0.100000            0.000000
25%        24.000000             0.130000        2.540000           91.000000
50%        49.000000             0.250000        5.030000          183.000000
75%        75.000000             0.380000        7.490000          273.000000
max        99.000000             0.500000       10.000000          364.000000

       promotion_id  customer_zip_code  store_zip_code  distance_to_store  \
count  20000.000000       20000.000000    20000.000000       20000.000000
mean     505.163200       55061.539350    54892.819950          49.871156
std      287.695868       26005.754689    25997.391743          28.856342
min        1.000000       10000.000000    10000.000000           0.010000
25%      259.000000       32756.250000    32266.750000          24.990000
50%      507.000000       54789.000000    54997.000000          49.715000
75%      753.000000       77617.500000    77304.250000          74.802500
max      999.000000       99998.000000    99998.000000         100.000000

       customer_support_calls  website_visits  days_since_last_purchase
count            20000.000000      20000.0000              20000.000000
mean                 9.450900         49.4241                181.558900
std                  5.760195         28.8630                105.631966
min                  0.000000          0.0000                  0.000000
25%                  4.000000         24.0000                 89.000000
50%                  9.000000         50.0000                182.000000
75%                 14.000000         74.0000                273.000000
max                 19.000000         99.0000                364.000000

Categorical Columns Statistics:
        gender income_bracket loyalty_program churned marital_status  \
count    20000          20000           20000   20000          20000
unique       3              3               2       2              3
top     Female         Medium             Yes      No        Married
freq      6735           6745           10062   10077           6737

       education_level     occupation product_category  payment_method  \
count            20000          20000            20000           20000
unique               4              4                5               4
top                PhD  Self-Employed      Electronics  Mobile Payment
freq              5178           5063             4127            5155

       store_location day_of_week purchase_frequency preferred_store  \
count           20000       20000              20000           20000
unique              4           7                  4               4
top        Location D    Saturday              Daily      Location C
freq             5046        2951               5026            5048

       product_name product_brand product_size product_color product_material  \
count         20000         20000        20000         20000            20000
unique            4             3            3             5                4
top       Product B       Brand Y        Small           Red            Metal
freq           5112          6695         6851          4071             5057

       promotion_type promotion_effectiveness promotion_channel  \
count           20000                   20000             20000
unique              3                       3                 3
top           20% Off                    High          In-store
freq             6698                    6705              6732

       promotion_target_audience customer_city customer_state store_city  \
count                      20000         20000          20000      20000
unique                         2             4              3          4
top          Returning Customers        City D        State Y     City B
freq                       10101          5084           6745       5043

       store_state holiday_season  season weekend email_subscriptions  \
count        20000          20000   20000   20000               20000
unique           3              2       4       2                   2
top        State X            Yes  Winter      No                  No
freq          6681          10103    5107   10035               10057

       app_usage social_media_engagement
count      20000                   20000
unique         3                       3
top       Medium                  Medium
freq        6756                    6767